version: '3.8'

services:
  namesrv:
    image: apache/rocketmq:5.3.2
    container_name: rmqnamesrv
    ports:
      - "9876:9876"
    command: sh mqnamesrv
    healthcheck:
      # test: ["CMD", "curl", "-f", "http://localhost:9876"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - rocketmq-network
  broker:
    image: apache/rocketmq:5.3.2
    container_name: rocketmq-broker
    ports:
      - "10911:10911"   # broker
      - "10909:10909"   # remoting
    depends_on:
      - namesrv
    environment:
      - NAMESRV_ADDR=namesrv:9876
      - JAVA_OPT_EXT=-Duser.home=/opt -Xms512m -Xmx512m -Xmn256m
    volumes:
      - ./data/logs:/home/rocketmq/logs
      - ./data/store:/home/rocketmq/store
      - ./broker.conf:/home/rocketmq/broker.conf
    command: sh mqbroker -n namesrv:9876 -c /home/rocketmq/broker.conf
    networks:
      - rocketmq-network

networks:
  rocketmq-network:
    driver: bridge 