server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mqtest
    username: root
    password: jiaze1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

rocketmq:
  name-server: localhost:9876
  producer:
    group: counter-producer-group
